spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: SELECT 1
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace
